<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>39ed904f-e112-43c8-b27e-776c939426e4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="OpenTelemetry" Version="1.13.1" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.13.1" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.13.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.13.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\BuildingBlock\BuildingBlock.csproj" />
    <ProjectReference Include="..\..\Shared\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\Utils\Utils.csproj" />
    <ProjectReference Include="..\ChatService.Application\ChatService.Application.csproj" />
    <ProjectReference Include="..\ChatService.Infrastructure\ChatService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
