services:
  chatapp.gateway:
    build: 
        context: .
        dockerfile: ./src/Gateway/ChatApp.Gateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      CHAT_BASE_URL: "http://chatservice.api:8080"
      HISTORY_BASE_URL: "http://historyservice.api:8080"
      PRESENCE_BASE_URL: "http://presenceservice.api:8080"
      DELIVERY_BASE_URL: "http://deliveryservice.api:8080"
      SIGNALING_BASE_URL: "http://signalingservice.api:8080"
    ports:
      - "8081:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      chatservice.api:
       condition: service_started
    networks:
      - chatnet

  chatservice.api:
    build:
        context: .
        dockerfile: ./src/ChatService/ChatService.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      KAFKA_BROKERS: kafka:9092
      KAFKA_CLIENT_ID: chatservice
    expose:
      - "8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - chatnet

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: chat
      POSTGRES_USER: chat
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U chat"]
        interval: 10s
        timeout: 5s
        retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatnet

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

    healthcheck:
        test: ["CMD-SHELL", "cub kafka-ready -b localhost:9092 1 1"]
        interval: 10s
        timeout: 5s
        retries: 5

    networks:
      - chatnet


  pgadmin:
     image: dpage/pgadmin4:latest
     environment:
         PGADMIN_DEFAULT_EMAIL: "admin@example.com"
         PGADMIN_DEFAULT_PASSWORD: "admin"
     ports:
         - "5050:80"
     volumes:
            - pgadmindata:/var/lib/pgadmin
     networks:
       - chatnet
     depends_on:
       postgres:
         condition: service_healthy
         
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: "local_chatapp"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_CLUSTERID: "MkU3OEVBNTcwNTJENDM2Qk"
    ports:
      - "8090:8080"
    networks:
      - chatnet
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  pgdata:
  pgadmindata:

networks:
  chatnet:
    driver: bridge
    name: chatapp_net  
