<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\BuildingBlock\BuildingBlock.csproj" />
    <ProjectReference Include="..\..\Shared\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\ChatService.Domain\ChatService.Domain.csproj" />
  </ItemGroup>

</Project>
